name: PHP8.1

on:
  workflow_dispatch:
  push:
    branches: [ 'develop' ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'amd64,arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push php-fpm:8.1
        uses: docker/build-push-action@v3
        with:
          context: php-fpm
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=8.1
          push: true
          tags: fgebauer/php-fpm:8.1, fgebauer/php-fpm:latest

      - name: Build and push php-fpm-nginx:8.1
        uses: docker/build-push-action@v3
        with:
          context: php-fpm-nginx
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=8.1
          push: true
          tags: fgebauer/php-fpm-nginx:8.1, fgebauer/php-fpm-nginx:latest